import { Sparkles } from "lucide-react";
import DiscoverForm from "./discover-form";

export default function DiscoverPage() {
  return (
    <div className="container mx-auto px-4 py-8 md:py-12">
      <div className="text-center mb-12">
        <Sparkles className="mx-auto h-12 w-12 text-primary mb-4" />
        <h1 className="text-4xl md:text-5xl font-headline font-bold">Discover Artifacts with AI</h1>
        <p className="mt-4 text-lg text-muted-foreground max-w-3xl mx-auto">
          Encountered an interesting mural, sculpture, or artifact? Upload a picture and a brief description to get detailed educational content generated by our AI.
        </p>
      </div>
      <div className="max-w-2xl mx-auto">
        <DiscoverForm />
      </div>
    </div>
  );
}
